wandb_version: 1

data_path:
  desc: null
  value: /media/mountHDD3/data_storage/z2h/ISIC/ISIC2017/all_data
image_size:
  desc: null
  value: 128
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 8.0e-05
num_steps:
  desc: null
  value: 500
gradient_accumulation:
  desc: null
  value: 2
ema_decay:
  desc: null
  value: 0.995
mixed_precision:
  desc: null
  value: true
calculate_fid:
  desc: null
  value: true
save_dir:
  desc: null
  value: ./models
checkpoint_interval:
  desc: null
  value: 10000
epochs:
  desc: null
  value: 1
timesteps:
  desc: null
  value: 1000
sampling_timesteps:
  desc: null
  value: 250
model_dim:
  desc: null
  value: 64
model_dim_mults:
  desc: null
  value:
  - 1
  - 2
  - 4
  - 8
flash_attn:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.7
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715850351.0
    t:
      1:
      - 1
      - 41
      - 55
      - 71
      2:
      - 1
      - 41
      - 55
      - 71
      3:
      - 13
      - 16
      - 23
      4: 3.10.7
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
